name: Dependabot Review & Merge

on:
  workflow_run:
    workflows: ["Dependabot Review"]
    types: [completed]
    # branches: [security-updates]
  
  push:
    branches: [test-workflows]

permissions:
  contents: write
  pull-requests: write

jobs:
  merge-pr:
    runs-on: ubuntu-latest
    if: ${{github.event.workflow_run.conclusion == 'success' && github.actor == 'dependabot[bot]'}}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: security-updates
      - name: Debug
        run: |
          echo "$GITHUB_ACTOR"
          echo "PULL_REQUEST_URL"
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          PULL_REQUEST_URL: ${{ github.event.pull_request.html_url }}
      - name: Enable auto-merge for Dependabot PRs
        # run: gh pr merge --auto --squash "$PR_URL"
        # env:
        #   PR_URL: ${{github.event.pull_request.html_url}}
        #   GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.workflow_run.pull_requests[0].number }}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
